// <auto-generated />
using System;
using System.Collections.Generic;
using Chess.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chess.Infrastructure.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    [Migration("20260522182922_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chess.Core.Entities.GameInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("Fens")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("FirstPlayerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActiveGame")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("Moves")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid?>("SecondPlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
