FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY Account.API/Account.API.csproj                           Account.API/
COPY Account.Application/Account.Application.csproj           Account.Application/
COPY Account.Core/Account.Core.csproj                         Account.Core/ 
COPY Account.Infrastructure/Account.Infrastructure.csproj     Account.Infrastructure/

RUN dotnet restore Account.API


WORKDIR /src/Account.API

ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://0.0.0.0:8080

EXPOSE 8080

CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080" ]
