<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

<ItemGroup>
  <None Include="Resources/MagicBitboards/magic_numbers_bishop.json" CopyToOutputDirectory="PreserveNewest" />
  <None Include="Resources/MagicBitboards/magic_numbers_rook.json" CopyToOutputDirectory="PreserveNewest" />
</ItemGroup>

</Project>
